title = "CLI Module Update and Project Structure"
status = { state = "ongoing" }
abstract = "Update CLI module from oh-my-commit to oh-my-commit and maintain project structure"

[[rounds]]
time = "2024-12-15T17:20:09+08:00"
round = 1
