[meta]
slug = "fix_types"
title = "Fix Type Errors"
abstract = "修复类型错误，包括 GitChangeSummary 和导入路径问题"

[[rounds]]
time = "2024-01-05T10:30:00Z"
round = 1
duration = 120

[[rounds]]
time = "2024-12-15T14:59:56+08:00"
round = 2
duration = 180
