name = "YAAC - Your Artistic Aide for Commits"
version = "2.0.0"
abstract = "本项目的目标是为 VSCode 提供一款高效、可靠的 AI 提交插件（YAAC），帮助开发者快速实现高质量的代码提交。\n"

[conversations.001]
slug = "tsc"
abstract = ""

[conversations.002]
slug = "pack"
abstract = ""

[conversations.003]
slug = "fix-treeview-expandeddirs"
abstract = ""

[conversations.004]
slug = "add-init-animation"
abstract = ""

[conversations.005]
slug = "vscode_plugin_architecture"
abstract = ""

[conversations.007]
slug = "vscode_extension_generator"
abstract = ""

[conversations.008]
slug = "git_implementation"
abstract = ""

[conversations.009]
slug = "vscode_extension_setup"
abstract = ""

[conversations.010]
slug = "yeoman_generator_behavior"
abstract = ""

[conversations.011]
slug = "vscode_task_error"
abstract = ""

[conversations.012]
slug = "vscode_extension_webview"
abstract = ""

[conversations.013]
slug = "vscode_extension_enhancement"
abstract = ""

[conversations.014]
slug = "vscode_plugin_error"
abstract = ""

[conversations.016]
slug = "vscode_debug"
abstract = ""

[conversations.018]
slug = "vscode_plugin_debug_solution"
abstract = ""

[conversations.019]
slug = "vscode_extension_template_debug"
abstract = ""

[conversations.020]
slug = "webview_floating"
abstract = ""

[conversations.021]
slug = "ui_mode_enhancement"
abstract = ""

[conversations.022]
slug = "fix_editor_actions"
abstract = ""

[conversations.023]
slug = "refactor_window_state"
abstract = ""

[conversations.024]
slug = "simplify_window_state"
abstract = ""

[conversations.025]
slug = "webview_titlebar_hide"
abstract = ""

[conversations.026]
slug = "logger_enhancement"
abstract = ""

[conversations.027]
slug = "simplify_fileitem"
abstract = ""

[conversations.028]
slug = "optimize_file_changes_layout"
abstract = "Optimize File Changes Layout"

[conversations.029]
slug = "diffviewer_no_changes"
abstract = "DiffViewer No Changes Investigation"

[conversations.030]
slug = "git_changes"
abstract = "Git Changes Implementation"
